# Generated by Django 3.2 on 2022-03-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
    ]
